version: '3.8'

name: voice-prod
services:
  ui:
    image: avin5644/voice-assistant-ui:v1
    container_name: voice_ui
    ports:
      - "8501:8501"
    environment:
      - ORCHESTRATOR_URL=http://orchestrator:8000
    volumes:
      - ./ui:/app  # Live reload for development
    networks:
      - voice-network

networks:
  voice-network:
    external: true
    name: voice_shared_net